### ISSUE TITLE
Proposal Response

### ISSUE THREAD

**Issue by jamesturk** [ghazalin/NH_inspections_static#1]
Hi, this looks great, these data sources look like there's a lot to work with and I look forward to seeing your results.

Regarding the PDF table, extraction from PDFs can be tricky as you may know, but the table isn't so large that it'd be impossible to copy into another file to make a CSV or list of Python objects. Let us know if you need assistance there and we can help you figure out the best path.

In terms of your question about scope: for now it's better to have lots of data to consider. I think that this will be reasonable and that doing comparisons between the two will be interesting and lend depth to your narrative, but if you find that dealing with all of them is cumbersome or doesn't add much to your analysis you can drop that portion and focus on the part that you determine to be most interesting and relevant for your analysis.

There's at least one other project with a focus on health and we'll try to group these into the same peer review group if possible, since even though they differ in focus, having people with subject area expertise will hopefully be mutually beneficial.

**Comment by ghazalin** [comment]
Thanks for your feedback!
